name: 'Appcircle Testing Distribution'
author: 'appcircleio'
description:
  "Efficiently distribute application builds to users or testing groups using
  Appcircle's robust platform."

branding:
  icon: 'icon.png'
  color: 'blue'

inputs:
  accessToken:
    description:
      'Provide the Appcircle access token to authenticate connections to
      Appcircle services. This token allows your Azure DevOps pipeline to
      interact with Appcircle for distributing applications'
    required: true
  profileID:
    description:
      'Enter the ID of the Appcircle distribution profile. This ID uniquely
      identifies the profile under which your applications will be distributed'
    required: true
  appPath:
    description:
      'Specify the path to your application file. For iOS, this can be a .ipa or
      .xcarchive file path. For Android, specify the .apk or .appbundle file
      path'
    required: true
  message:
    description:
      'Message to include with the distribution to provide additional
      information to testers or users receiving the build'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
