name: 'Appcircle Testing Distribution'
author: 'appcircleio'
description:
  "Appcircle Testing Distribution enables the binary distribution of Android
  (.apk, .aab) and iOS (.ipa) files, allowing teams to create test groups and
  share builds using enterprise authentication methods such as SSO and LDAP."

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  personalAPIToken:
    description:
      'Provide Appcircle Personal API Token to authenticate Appcircle services.'
    required: true
  authEndpoint:
    description:
      'Optional: Authentication endpoint URL for self-hosted Appcircle
      installations. Defaults to the Appcircle cloud.'
    required: false
    default: 'https://auth.appcircle.io'
  apiEndpoint:
    description:
      'Optional: API endpoint URL for self-hosted Appcircle installations.
      Defaults to the Appcircle cloud.'
    required: false
    default: 'https://api.appcircle.io'
  profileName:
    description:
      'Enter the profile name of the Appcircle distribution profile. This name
      uniquely identifies the profile under which your applications will be
      distributed'
    required: true
  createProfileIfNotExists:
    description:
      'Specify whether to create a new app profile if one does not already
      exist.'
    required: true
    type: boolean
  appPath:
    description:
      'Specify the path to your application file. For iOS, this can be a .ipa or
      .xcarchive file path. For Android, specify the .apk or .appbundle file
      path'
    required: true
  message:
    description:
      'Message to include with the distribution to provide additional
      information to testers or users receiving the build'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'
